# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5a6284d3405a8a678293bf8f953ec61867fe73bfc0723ea38ab157c90030589ba8c1b79292ebfadd5d76841f44983f0dfd228b5511a12f96103a0631fe0a8ca

test:
  secret_key_base: da133e4c52ff49222f0e3fe1095b55066dee7f0cea0cc5275f4284aecbea08d68a3f53e4577aff275ca6907cafd124f950cb750af880fc2e96a243209830fd20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
